title: 小萝卜的工作Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: 给自己的学习和工作目标规划好deadline~
author: Abhishek Das

domain: "aideadlin.es"
baseurl: ""

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: abhshkdz
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']